
name: Terraform (Artifactory Remote Backend)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "terraform-artifactory-remote-demo/**"

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-artifactory-remote-demo

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure Terraform CLI creds for your JFrog host
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          cli_config_credentials_hostname: trialpf4dwg.jfrog.io
          cli_config_credentials_token: ${{ secrets.JFROG_ACCESS_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
