
name: Terraform Cloud Deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      # Terraform Cloud supports token environment variables
      TFE_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
          

      # Optional way to write credentials.tfrc.json manually
      - name: Write Terraform Cloud credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TFC_TOKEN }}"
              }
            }
          }
          EOF

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.14.3
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraformCloud"
          
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan     
